#[cfg(any(feature = "mock", test))]
use crate::models::{AgentStatus, NavigationNode};

/// Return a static set of mock navigation nodes for testing the UI without a live Herdr socket.
///
/// Covers all AgentStatus variants, multiple workspaces/tabs, and enough items
/// to exercise scrolling, filtering, highlighting, and edge cases.
#[cfg(any(feature = "mock", test))]
pub fn mock_nodes() -> Vec<NavigationNode> {
    vec![
        // ── Auth-Service workspace (ws-1) ──
        NavigationNode {
            workspace_id: "ws-1".into(),
            workspace_name: "Auth-Service".into(),
            tab_id: "tab-2".into(),
            tab_name: "Main".into(),
            pane_id: "pane-1".into(),
            pane_name: Some("agent-01".into()),
            agent_id: Some("claude".into()),
            agent_status: AgentStatus::Blocked,
            last_accessed_at: 5000,
            state_change_seq: 0,
        },
        NavigationNode {
            workspace_id: "ws-1".into(),
            workspace_name: "Auth-Service".into(),
            tab_id: "tab-1".into(),
            tab_name: "Config".into(),
            pane_id: "pane-4".into(),
            pane_name: Some("pane-03".into()),
            agent_id: Some("agent-01".into()),
            agent_status: AgentStatus::Working,
            last_accessed_at: 2000,
            state_change_seq: 0,
        },
        NavigationNode {
            workspace_id: "ws-1".into(),
            workspace_name: "Auth-Service".into(),
            tab_id: "tab-1".into(),
            tab_name: "Config".into(),
            pane_id: "pane-3".into(),
            pane_name: Some("pane3".into()),
            agent_id: Some("gemini".into()),
            agent_status: AgentStatus::Working,
            last_accessed_at: 6000,
            state_change_seq: 0,
        },
        NavigationNode {
            workspace_id: "ws-1".into(),
            workspace_name: "Auth-Service".into(),
            tab_id: "tab-3".into(),
            tab_name: "Secrets".into(),
            pane_id: "pane-6".into(),
            pane_name: Some("vault-01".into()),
            agent_id: Some("ansible".into()),
            agent_status: AgentStatus::Done,
            last_accessed_at: 1800,
            state_change_seq: 0,
        },
        // ── Backend-Repo workspace (ws-2) ──
        NavigationNode {
            workspace_id: "ws-2".into(),
            workspace_name: "Backend-Repo".into(),
            tab_id: "tab-1".into(),
            tab_name: "Dev".into(),
            pane_id: "pane-2".into(),
            pane_name: Some("pane-02".into()),
            agent_id: Some("opencode".into()),
            agent_status: AgentStatus::Done,
            last_accessed_at: 4000,
            state_change_seq: 0,
        },
        NavigationNode {
            workspace_id: "ws-2".into(),
            workspace_name: "Backend-Repo".into(),
            tab_id: "tab-2".into(),
            tab_name: "API".into(),
            pane_id: "pane-7".into(),
            pane_name: Some("router-01".into()),
            agent_id: Some("envoy".into()),
            agent_status: AgentStatus::Working,
            last_accessed_at: 3500,
            state_change_seq: 0,
        },
        NavigationNode {
            workspace_id: "ws-2".into(),
            workspace_name: "Backend-Repo".into(),
            tab_id: "tab-2".into(),
            tab_name: "API".into(),
            pane_id: "pane-8".into(),
            pane_name: Some("db-pool".into()),
            agent_id: Some("pgadmin".into()),
            agent_status: AgentStatus::Idle,
            last_accessed_at: 1200,
            state_change_seq: 0,
        },
        // ── Frontend-UI workspace (ws-3) ──
        NavigationNode {
            workspace_id: "ws-3".into(),
            workspace_name: "Frontend-UI".into(),
            tab_id: "tab-3".into(),
            tab_name: "Design".into(),
            pane_id: "pane-3".into(),
            pane_name: Some("pane-01".into()),
            agent_id: None,
            agent_status: AgentStatus::Idle,
            last_accessed_at: 3000,
            state_change_seq: 0,
        },
        NavigationNode {
            workspace_id: "ws-3".into(),
            workspace_name: "Frontend-UI".into(),
            tab_id: "tab-3".into(),
            tab_name: "Design".into(),
            pane_id: "pane-9".into(),
            pane_name: Some("sketch-pad".into()),
            agent_id: Some("figma-bot".into()),
            agent_status: AgentStatus::Working,
            last_accessed_at: 2800,
            state_change_seq: 0,
        },
        NavigationNode {
            workspace_id: "ws-3".into(),
            workspace_name: "Frontend-UI".into(),
            tab_id: "tab-4".into(),
            tab_name: "Components".into(),
            pane_id: "pane-10".into(),
            pane_name: Some("storybook".into()),
            agent_id: Some("chromatic".into()),
            agent_status: AgentStatus::Done,
            last_accessed_at: 2200,
            state_change_seq: 0,
        },
        // ── Infra-Deploy workspace (ws-4) — no agents ──
        NavigationNode {
            workspace_id: "ws-4".into(),
            workspace_name: "Infra-Deploy".into(),
            tab_id: "tab-1".into(),
            tab_name: "Prod".into(),
            pane_id: "pane-5".into(),
            pane_name: Some("pane-04".into()),
            agent_id: None,
            agent_status: AgentStatus::None,
            last_accessed_at: 1000,
            state_change_seq: 0,
        },
        NavigationNode {
            workspace_id: "ws-4".into(),
            workspace_name: "Infra-Deploy".into(),
            tab_id: "tab-2".into(),
            tab_name: "Staging".into(),
            pane_id: "pane-11".into(),
            pane_name: Some("helm-01".into()),
            agent_id: None,
            agent_status: AgentStatus::None,
            last_accessed_at: 800,
            state_change_seq: 0,
        },
        // ── ML-Pipeline workspace (ws-5) — many agents ──
        NavigationNode {
            workspace_id: "ws-5".into(),
            workspace_name: "ML-Pipeline".into(),
            tab_id: "tab-1".into(),
            tab_name: "Training".into(),
            pane_id: "pane-12".into(),
            pane_name: Some("train-node".into()),
            agent_id: Some("pytorch".into()),
            agent_status: AgentStatus::Working,
            last_accessed_at: 4500,
            state_change_seq: 0,
        },
        NavigationNode {
            workspace_id: "ws-5".into(),
            workspace_name: "ML-Pipeline".into(),
            tab_id: "tab-1".into(),
            tab_name: "Training".into(),
            pane_id: "pane-13".into(),
            pane_name: Some("data-aug".into()),
            agent_id: Some("albumentations".into()),
            agent_status: AgentStatus::Working,
            last_accessed_at: 4200,
            state_change_seq: 0,
        },
        NavigationNode {
            workspace_id: "ws-5".into(),
            workspace_name: "ML-Pipeline".into(),
            tab_id: "tab-2".into(),
            tab_name: "Evaluation".into(),
            pane_id: "pane-14".into(),
            pane_name: Some("eval-node".into()),
            agent_id: Some("sklearn".into()),
            agent_status: AgentStatus::Blocked,
            last_accessed_at: 3800,
            state_change_seq: 0,
        },
        NavigationNode {
            workspace_id: "ws-5".into(),
            workspace_name: "ML-Pipeline".into(),
            tab_id: "tab-2".into(),
            tab_name: "Evaluation".into(),
            pane_id: "pane-15".into(),
            pane_name: Some("confusion-matrix".into()),
            agent_id: None,
            agent_status: AgentStatus::Idle,
            last_accessed_at: 1600,
            state_change_seq: 0,
        },
        NavigationNode {
            workspace_id: "ws-5".into(),
            workspace_name: "ML-Pipeline".into(),
            tab_id: "tab-3".into(),
            tab_name: "Deploy".into(),
            pane_id: "pane-16".into(),
            pane_name: Some("model-serve".into()),
            agent_id: Some("triton".into()),
            agent_status: AgentStatus::Done,
            last_accessed_at: 1400,
            state_change_seq: 0,
        },
        // ── Data-Lake workspace (ws-6) ──
        NavigationNode {
            workspace_id: "ws-6".into(),
            workspace_name: "Data-Lake".into(),
            tab_id: "tab-1".into(),
            tab_name: "Ingestion".into(),
            pane_id: "pane-17".into(),
            pane_name: Some("kafka-01".into()),
            agent_id: Some("kafka-bot".into()),
            agent_status: AgentStatus::Working,
            last_accessed_at: 3200,
            state_change_seq: 0,
        },
        NavigationNode {
            workspace_id: "ws-6".into(),
            workspace_name: "Data-Lake".into(),
            tab_id: "tab-2".into(),
            tab_name: "Analytics".into(),
            pane_id: "pane-18".into(),
            pane_name: Some("spark-01".into()),
            agent_id: Some("spark-bot".into()),
            agent_status: AgentStatus::Blocked,
            last_accessed_at: 2500,
            state_change_seq: 0,
        },
        NavigationNode {
            workspace_id: "ws-6".into(),
            workspace_name: "Data-Lake".into(),
            tab_id: "tab-2".into(),
            tab_name: "Analytics".into(),
            pane_id: "pane-19".into(),
            pane_name: Some("delta-table".into()),
            agent_id: None,
            agent_status: AgentStatus::None,
            last_accessed_at: 900,
            state_change_seq: 0,
        },
        // ── API-Gateway workspace (ws-7) — single pane, no agent ──
        NavigationNode {
            workspace_id: "ws-7".into(),
            workspace_name: "API-Gateway".into(),
            tab_id: "tab-1".into(),
            tab_name: "Routes".into(),
            pane_id: "pane-20".into(),
            pane_name: Some("kong-01".into()),
            agent_id: None,
            agent_status: AgentStatus::None,
            last_accessed_at: 700,
            state_change_seq: 0,
        },
        // ── Mobile-App workspace (ws-8) ──
        NavigationNode {
            workspace_id: "ws-8".into(),
            workspace_name: "Mobile-App".into(),
            tab_id: "tab-1".into(),
            tab_name: "iOS".into(),
            pane_id: "pane-21".into(),
            pane_name: Some("xcode-preview".into()),
            agent_id: Some("swift-bot".into()),
            agent_status: AgentStatus::Working,
            last_accessed_at: 2100,
            state_change_seq: 0,
        },
        NavigationNode {
            workspace_id: "ws-8".into(),
            workspace_name: "Mobile-App".into(),
            tab_id: "tab-2".into(),
            tab_name: "Android".into(),
            pane_id: "pane-22".into(),
            pane_name: Some("emulator-01".into()),
            agent_id: Some("kotlin-bot".into()),
            agent_status: AgentStatus::Working,
            last_accessed_at: 1900,
            state_change_seq: 0,
        },
    ]
}
